//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestsDetail
    {
        public int ContestId { get; set; }
        public string ContestName { get; set; }
        public Nullable<int> EntryAmount { get; set; }
    }
}
