//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletsAccount
    {
        public int WalletId { get; set; }
        public Nullable<int> DepositBucket { get; set; }
        public Nullable<int> BonusBucket { get; set; }
        public Nullable<int> WinningsBucket { get; set; }
        public Nullable<int> TotalWalletAmount { get; set; }
    }
}
